project_name: unboot

before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-build
    main: ./main.go
    env: [CGO_ENABLED=1]
    goos: [darwin]
    goarch: [amd64]

archives:
  - id: darwin-build
    builds: [darwin-build]
    replacements:
      darwin: Darwin
      amd64: x86_64

brews:
  - ids: [darwin-build]
    tap:
      owner: echocrow
      name: homebrew-tap
    folder: Formula

    homepage: '{{ replace .GitURL ".git" "" }}'
    description: A simple CLI to shutdown or restart macOS.
    license: MIT

    test: |
      system "#{bin}/unboot", "-version"
